### ISSUE TITLE
Request for transfer: power-assert-js organization

### ISSUE THREAD

**Issue by twada** [power-assert-js/espower-typescript#1]
Hi @teppeis, I've created new organization [power-assert-js](https://github.com/power-assert-js) to help users to find related products easily, and I want you to transfer this project to power-assert-js org.

If you agree with me, please see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by teppeis** [comment]
Sure! I'll try! :smile_cat:

**Comment by teppeis** [comment]
@twada done! sorry to be late.

**Comment by twada** [comment]
@teppeis Thanks a lot!!
