### ISSUE TITLE
TypeScript 2.0

### ISSUE THREAD

**Issue by niieani** [power-assert-js/espower-typescript#17]
Any timeframe for TS 2.0 support?

**Comment by teppeis** [comment]
@niieani I'll support it just after TS 2.0 stable is released.
https://github.com/Microsoft/TypeScript/milestone/24

**Comment by danielmoore** [comment]
@teppeis Any roadmap for supporting TS 2.0 now that it's been released?

**Comment by teppeis** [comment]
@niieani @danielmoore I've released TypeScript 2.0 support in v6.0.0.
