### ISSUE TITLE
*.tsx support?

### ISSUE THREAD

**Issue by Pleasurazy** [power-assert-js/espower-typescript#27]
Hello~ thanks for this awesome project.

I know #10 mentioned `*.tsx` files are supported in `4.x`.

But I using espower-typescript@8.0.0 seems not working.

It's working with `.ts`

![image](https://cloud.githubusercontent.com/assets/1500206/24488589/66ebf2fe-154a-11e7-8378-fc0081cc327a.png)

![image](https://cloud.githubusercontent.com/assets/1500206/24488621/acfea2e6-154a-11e7-9cc2-b4995c930802.png)

But not working if I change filename to `.tsx` from `.ts`

![image](https://cloud.githubusercontent.com/assets/1500206/24488618/a480a31c-154a-11e7-9bd7-1d6cc79dc3c4.png)

![image](https://cloud.githubusercontent.com/assets/1500206/24488613/9fced794-154a-11e7-9d0c-6667734a1290.png)

Am I missing something?

**Comment by teppeis** [comment]
@Pleasurazy I've published this feature in v8.1.0 🚀 
Thank you for waiting!
