### ISSUE TITLE
support loading different tsconfig in specific env

### ISSUE THREAD

**Issue by echopi** [power-assert-js/espower-typescript#32]
In my scenario, I have to tsconfig files, they are `tsconfig.json` for production env and `tsconfig.test.json` for test env. How can I distinguish them when using espower-typescript? 

Thanks.

**Comment by teppeis** [comment]
@echopi Copy `guess.js` and modify [this part](https://github.com/power-assert-js/espower-typescript/blob/7835330b2d3f898d369d92ea88b179596596b195/guess.js#L17-L23) for your needs.
