### ISSUE TITLE
Use other config file name in zero-config mode

### ISSUE THREAD

**Issue by tai2** [power-assert-js/espower-typescript#38]
There is no way to change the typescript config file name in zero config mode as I figure out.

Must I set it up manually to change the config file name, say `tsconfig.test.json`,  instead of using zero-config mode?

How about supporting environment variable for `ts.findConfigFile`'s third argument?

**Comment by teppeis** [comment]
v9 uses [ts-node](https://github.com/TypeStrong/ts-node) internally.
You could use `TS_NODE_PROJECT` env to solve this issue.
