### ISSUE TITLE
ts-coverage?

### ISSUE THREAD

**Issue by JaKXz** [power-assert-js/espower-typescript#6]
First of all, thank you! This package has helped me immensely.

Is there any (easy) way currently to instrument TypeScript code before its transpilation to JS and get code coverage on it with something like Istanbul? The ideal setup would look something like [coffee-coverage](https://github.com/benbria/coffee-coverage).

**Comment by vvakame** [comment]
FYI: https://github.com/gotwarlost/istanbul/issues/212

**Comment by JaKXz** [comment]
I have seen that issue, but it doesn't look like there's a resolution atm. I'll close this issue in favour of that, though. Thanks.
